---
swagger: '2.0'
info:
  title: BookKeeping API
  description: Use to track your everyday finance.
  version: "0.0.1"
# the domain of the service
host: api.
# array of all schemes that your API supports
schemes:
  - https
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTPS`
# will be prefixed to all paths
basePath: /v0
produces:
  - application/json
paths:
  /records:
    # Inquery all book keeping record
    get:
      security:
       - basicAuth: []
      summary:  Inquery all book keeping record.
      description: |
        This endpoint use to inquery all book keeping record with some filter.
      parameters:
        - name: user_id
          in: query
          description: User id to be inquery.
          required: true
          type: string
        - name: start_date
          in: query
          description: Start date of records to be inquery.
          required: false
          type: string
          format: date
        - name: end_date
          in: query
          description: End date of records to be inquery.
          required: false
          type: string
          format: date
        - name: record_type
          in: query
          description: Record type to be inquery.
          required: false
          type: string
        - name: account_id
          in: query
          description: Account of records to be inquery.
          required: false
          type: string
        - name: currency_code
          in: query
          description: Currency of records to be inquery. "[ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code."
          required: false
          type: string
      tags:
        - Inquery
      responses:
        200:
          description: An array of records.
          schema:
            type: array
            items:
              $ref: '#/definitions/BookKeepingRecord'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /records/{record_id}:
    # Inquery specific book keeping record
    get:
      security:
       - basicAuth: []
      summary:  Inquery specific book keeping record.
      description: |
        This endpoint use to inquery specific book keeping record with record id.
      parameters:
        - name: user_id
          in: query
          description: User id to be inquery.
          required: true
          type: string
        - name: record_id
          in: path
          description: Record id to be inquery.
          required: true
          type: string
      tags:
        - Inquery
      responses:
        200:
          description: A record.
          schema:
            $ref: '#/definitions/BookKeepingRecord'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /records/balances:
    # Inquery specific user's accounts balance at specific date
    get:
      security:
       - basicAuth: []
      summary:  Inquery specific user's accounts balance at specific date
      description: |
        This endpoint use to inquery specific user's accounts balance at specific date.
      parameters:
        - name: user_id
          in: query
          description: User id to be inquery.
          required: true
          type: string
        - name: balance_date
          in: query
          description: Balance date to be inquery.
          required: true
          type: string
          format: date
      tags:
        - Inquery
      responses:
        200:
          description: An array of account balance.
          schema:
            $ref: '#/definitions/AccountBalance'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /records/expenses:
    # Create new expense record
    post:
      security:
       - basicAuth: []
      summary:  Create new expense record.
      description: |
        This endpoint use to add a new expense reocrd.
      parameters:
        - name: date
          in: query
          description: Date of expense record.
          required: true
          type: string
          format: date
        - name: currency_code
          in: query
          description: currency of expense
          required: true
          type: string
        - name: amount
          in: query
          description: Amount of expense
          required: true
          type: number
          format: double
          # TODO: Complete all parameters
      tags:
        - Expenses
      responses:
        200:
          description: Confirmation of record created.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /records/expenses/{expense_record_id}:
    # Update specific expense record
    put:
      security:
       - basicAuth: []
      summary:  Update specific expense record.
      description: |
        This endpoint use to update specific expense reocrd.
      parameters:
        - name: expense_record_id
          in: path
          description: Record id of specific expense record.
          required: true
          type: integer
          format: int32
        - name: currency_code
          in: query
          description: currency of expense
          required: false
          type: string
        - name: amount
          in: query
          description: Amount of expense
          required: true
          type: number
          format: double
          # TODO: Complete all parameters
      tags:
        - Expenses
      responses:
        200:
          description: Confirmation of record updated.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    # Delete specific expense record
    delete:
      security:
       - basicAuth: []
      summary:  Delete specific expense record.
      description: |
        This endpoint use to delete specific expense reocrd.
      parameters:
        - name: expense_record_id
          in: path
          description: Record id of specific expense record.
          required: true
          type: integer
          format: int32
      tags:
        - Expenses
      responses:
        200:
          description: Confirmation of record deleted.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /records/incomes:
    # Create new income record
    post:
      security:
       - basicAuth: []
      summary:  Create new income record.
      description: |
        This endpoint use to add a new income reocrd.
      parameters:
        - name: date
          in: query
          description: Date of income record.
          required: true
          type: string
          format: date
        - name: currency_code
          in: query
          description: currency of income
          required: true
          type: string
        - name: amount
          in: query
          description: Amount of income
          required: true
          type: number
          format: double
          # TODO: Complete all parameters
      tags:
        - Incomes
      responses:
        200:
          description: Confirmation of record created.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /records/incomes/{income_record_id}:
    # Update specific income record
    put:
      security:
       - basicAuth: []
      summary:  Update specific income record.
      description: |
        This endpoint use to update specific income reocrd.
      parameters:
        - name: income_record_id
          in: path
          description: Record id of specific income record.
          required: true
          type: integer
          format: int32
        - name: currency_code
          in: query
          description: currency of income
          required: false
          type: string
        - name: amount
          in: query
          description: Amount of income
          required: true
          type: number
          format: double
          # TODO: Complete all parameters
      tags:
        - Incomes
      responses:
        200:
          description: Confirmation of record updated.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    # Delete specific income record
    delete:
      security:
       - basicAuth: []
      summary:  Delete specific income record.
      description: |
        This endpoint use to delete specific income reocrd.
      parameters:
        - name: income_record_id
          in: path
          description: Record id of specific income record.
          required: true
          type: integer
          format: int32
      tags:
        - Incomes
      responses:
        200:
          description: Confirmation of record deleted.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /records/transfers:
    # Create new transfer record
    post:
      security:
       - basicAuth: []
      summary:  Create new transfer record.
      description: |
        This endpoint use to add a new transfer reocrd.
      parameters:
        - name: date
          in: query
          description: Date of transfer record.
          required: true
          type: string
          format: date
        - name: currency_code
          in: query
          description: currency of transfer
          required: true
          type: string
        - name: amount
          in: query
          description: Amount of transfer
          required: true
          type: number
          format: double
          # TODO: Complete all parameters
      tags:
        - Transfers
      responses:
        200:
          description: Confirmation of record created.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /records/transfers/{transfer_record_id}:
    # Update specific transfer record
    put:
      security:
       - basicAuth: []
      summary:  Update specific transfer record.
      description: |
        This endpoint use to update specific transfer reocrd.
      parameters:
        - name: transfer_record_id
          in: path
          description: Record id of specific transfer record.
          required: true
          type: integer
          format: int32
        - name: currency_code
          in: query
          description: currency of transfer
          required: false
          type: string
        - name: amount
          in: query
          description: Amount of transfer
          required: true
          type: number
          format: double
          # TODO: Complete all parameters
      tags:
        - Transfers
      responses:
        200:
          description: Confirmation of record updated.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    # Delete specific transfer record
    delete:
      security:
       - basicAuth: []
      summary:  Delete specific transfer record.
      description: |
        This endpoint use to delete specific transfer reocrd.
      parameters:
        - name: transfer_record_id
          in: path
          description: Record id of specific transfer record.
          required: true
          type: integer
          format: int32
      tags:
        - Transfers
      responses:
        200:
          description: Confirmation of record deleted.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /records/subjects/:
    # Inquery all subjects
    get:
      security:
       - basicAuth: []
      summary:  Inquery all subjects by user id.
      description: |
        This endpoint use to inquery all subjects by user id.
      parameters:
        - name: user_id
          in: query
          description: User id to be inquery.
          required: true
          type: string
        - name: subject_status
          in: query
          description: subject_status to be inquery.
          required: false
          type: string
      tags:
        - Inquery
      responses:
        200:
          description: An array of subjects.
          schema:
            type: array
            items:
              $ref: '#/definitions/Subject'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users:
    # Create new user
    post:
      security:
       - basicAuth: []
      summary: Create user
      description: |
        This endpoint use to create new user.
      parameters:
        - name: body
          in: body
          description: User object to be created.
          required: true
          schema:
            $ref: "#/definitions/User"
      tags:
        - user
      responses:
        200:
          description: Confirmation of user created.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users/{user_id}:
    # Update specific user
    put:
      security:
       - basicAuth: []
      summary: Update specific user
      description: |
        This endpoint use to update specific user.
      parameters:
        - name: user_id
          in: path
          description: user id that need to be updated
          required: true
          type: string
        - name: body
          in: body
          description: Updated user object
          required: true
          schema:
            $ref: "#/definitions/User"
      tags:
        - user
      responses:
        200:
          description: Confirmation of record created.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    # Delete specific user
    delete:
      security:
       - basicAuth: []
      summary: Delete specific user
      description: |
        This endpoint use to delete specific user.
      parameters:
        - name: user_id
          in: path
          description: user id that need to be delete
          required: true
          type: string
      tags:
        - user
      responses:
        200:
          description: Confirmation of record deleted.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users/login:
    # Logs user into the system
    get:
      security:
       - basicAuth: []
      summary: Logs user into the system
      description: |
        This endpoint use to logs user into the system.
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: true
          type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          type: string
      tags:
        - user
      responses:
        200:
          description: login successful
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users/logout:
    # Logs out current logged in user session
    get:
      security:
       - basicAuth: []
      summary: Logs out current logged in user session
      description: |
        This endpoint use to logs out current logged in user session.
      parameters:
        - name: username
          in: query
          description: The user name for logout
          required: true
          type: string
      tags:
        - user
      responses:
        200:
          description: logout successful
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  BookKeepingRecord:
    type: object
    properties:
      user_id:
        type: string
      record_id:
        type: integer
        format: int32
      record_type:
        type: string
      subject_id:
        type: string
      subject_name:
        type: string
      subsubject_id:
        type: string
      subsubject_name:
        type: string
      account_id:
        type: string
      account_name:
        type: string
      receipt_no:
        type: string
      receipt_volumn:
        type: integer
        format: int32
      currency_code:
        type: string
        description: "[ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code."
      amount:
        type: number
        format: double
      currency_code_transfer_in:
        type: string
        description: "[ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code."
      amount_transfer_in:
        type: number
        format: double
      memo:
        type: string
  AccountBalance:
    type: object
    properties:
      user_id:
        type: string
      account_id:
        type: string
      balance_date:
        type: string
        format: date
      account_currency:
        type: string
        description: "[ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code."
      account_balance:
        type: integer
        format: int32
  Subject:
    type: object
    properties:
      user_id:
        type: string
      subject_id:
        type: string
      subject_name:
        type: string
      subject_type:
        type: string
      subject_status:
        type: string
      subject_order:
        type: integer
        format: int32
      subsubject:
        $ref: '#/definitions/Subsubject'
  Subsubject:
    type: object
    properties:
      subsubject_id:
        type: string
      subsubject_name:
        type: string
      subsubject_status:
        type: string
      subsubject_order:
        type: integer
        format: int32
  User:
    type: object
    properties:
      user_id:
        type: string
      user_name:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      password:
        type: string
        format: password
      user_status:
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
